package gov.customs.rule.data;

// Generated Jun 26, 2015 2:18:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * EntityMappingView generated by hbm2java
 */
public class EntityMappingView implements java.io.Serializable {

	private EntityMappingViewId id;

	public EntityMappingView() {
	}

	public EntityMappingView(EntityMappingViewId id) {
		this.id = id;
	}

	public EntityMappingViewId getId() {
		return this.id;
	}

	public void setId(EntityMappingViewId id) {
		this.id = id;
	}

}
