package gov.customs.rule.data;

// Generated Jun 26, 2015 2:18:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * EntityJar generated by hbm2java
 */
public class EntityJar implements java.io.Serializable {

	private long id;
	private String subSystem;
	private String jarFullpath;
	private String jarName;

	public EntityJar() {
	}

	public EntityJar(long id) {
		this.id = id;
	}

	public EntityJar(long id, String subSystem, String jarFullpath,
			String jarName) {
		this.id = id;
		this.subSystem = subSystem;
		this.jarFullpath = jarFullpath;
		this.jarName = jarName;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getSubSystem() {
		return this.subSystem;
	}

	public void setSubSystem(String subSystem) {
		this.subSystem = subSystem;
	}

	public String getJarFullpath() {
		return this.jarFullpath;
	}

	public void setJarFullpath(String jarFullpath) {
		this.jarFullpath = jarFullpath;
	}

	public String getJarName() {
		return this.jarName;
	}

	public void setJarName(String jarName) {
		this.jarName = jarName;
	}

}
