package gov.customs.rule.data;

// Generated Jun 26, 2015 2:18:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * EntityMappingViewId generated by hbm2java
 */
public class EntityMappingViewId implements java.io.Serializable {

	private long id;
	private String key;
	private String name;
	private String classFullname;
	private String domain;
	private Long jarId;
	private String jarFullpath;

	public EntityMappingViewId() {
	}

	public EntityMappingViewId(long id) {
		this.id = id;
	}

	public EntityMappingViewId(long id, String key, String name,
			String classFullname, String domain, Long jarId, String jarFullpath) {
		this.id = id;
		this.key = key;
		this.name = name;
		this.classFullname = classFullname;
		this.domain = domain;
		this.jarId = jarId;
		this.jarFullpath = jarFullpath;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getClassFullname() {
		return this.classFullname;
	}

	public void setClassFullname(String classFullname) {
		this.classFullname = classFullname;
	}

	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public Long getJarId() {
		return this.jarId;
	}

	public void setJarId(Long jarId) {
		this.jarId = jarId;
	}

	public String getJarFullpath() {
		return this.jarFullpath;
	}

	public void setJarFullpath(String jarFullpath) {
		this.jarFullpath = jarFullpath;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EntityMappingViewId))
			return false;
		EntityMappingViewId castOther = (EntityMappingViewId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getKey() == castOther.getKey()) || (this.getKey() != null
						&& castOther.getKey() != null && this.getKey().equals(
						castOther.getKey())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getClassFullname() == castOther.getClassFullname()) || (this
						.getClassFullname() != null
						&& castOther.getClassFullname() != null && this
						.getClassFullname()
						.equals(castOther.getClassFullname())))
				&& ((this.getDomain() == castOther.getDomain()) || (this
						.getDomain() != null && castOther.getDomain() != null && this
						.getDomain().equals(castOther.getDomain())))
				&& ((this.getJarId() == castOther.getJarId()) || (this
						.getJarId() != null && castOther.getJarId() != null && this
						.getJarId().equals(castOther.getJarId())))
				&& ((this.getJarFullpath() == castOther.getJarFullpath()) || (this
						.getJarFullpath() != null
						&& castOther.getJarFullpath() != null && this
						.getJarFullpath().equals(castOther.getJarFullpath())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result
				+ (getKey() == null ? 0 : this.getKey().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37
				* result
				+ (getClassFullname() == null ? 0 : this.getClassFullname()
						.hashCode());
		result = 37 * result
				+ (getDomain() == null ? 0 : this.getDomain().hashCode());
		result = 37 * result
				+ (getJarId() == null ? 0 : this.getJarId().hashCode());
		result = 37
				* result
				+ (getJarFullpath() == null ? 0 : this.getJarFullpath()
						.hashCode());
		return result;
	}

}
