package gov.customs.rule.data;

// Generated Jun 26, 2015 2:18:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * EntityMapping generated by hbm2java
 */
public class EntityMapping implements java.io.Serializable {

	private long id;
	private String key;
	private String name;
	private String classFullname;
	private String domain;
	private Long jarId;

	public EntityMapping() {
	}

	public EntityMapping(long id) {
		this.id = id;
	}

	public EntityMapping(long id, String key, String name,
			String classFullname, String domain, Long jarId) {
		this.id = id;
		this.key = key;
		this.name = name;
		this.classFullname = classFullname;
		this.domain = domain;
		this.jarId = jarId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getClassFullname() {
		return this.classFullname;
	}

	public void setClassFullname(String classFullname) {
		this.classFullname = classFullname;
	}

	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public Long getJarId() {
		return this.jarId;
	}

	public void setJarId(Long jarId) {
		this.jarId = jarId;
	}

}
